import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
const inter=Inter({subsets:["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <ClerkProvider>
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${inter.className}`}>
     <Header/>
      <main className="min-h-screen">
      {children}
      </main>
      <footer className="py-8 px-4 border-t" >
      <div className="max-w-6xl mx-auto flex justify-center items-center" >
        <p>love you jaan</p>
      </div>
      </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
